GET http://localhost:5000/healthcheck

###
POST http://localhost:5000/signup
content-type: application/json

{
  "username": "ThomasTest1",
  "email": "thomas@test.com",
  "password": "Hunter20"
}

###
POST http://localhost:5000/login
content-type: application/json

{
  "username": "ThomasTest1",
  "password": "Hunter20"
}